fix: git submodule

diff --git a/monodevelop-docker b/monodevelop-docker
--- a/monodevelop-docker
+++ b/monodevelop-docker
@@ -2,29 +2,36 @@
 
 DOCKERCONTAINER="monodevelop-docker-container"
 COUNTER=0
+MAX_COUNTER=100
 
 # check for empty docker container
-while [  $COUNTER -lt 100 ]; do
+while [  $COUNTER -lt $MAX_COUNTER ]; do
     # increase counter 
     let COUNTER=COUNTER+1 
-    # check for presence of process with specific docker container
-    if ! pgrep -f "$DOCKERCONTAINER$COUNTER" >/dev/null 2>&1 ; then
-        # process not present, use this docker container to run
-        echo -e "founded empty docker container: $DOCKERCONTAINER$COUNTER"
-        break
+    CONTAINER_NAME="$DOCKERCONTAINER$COUNTER"
+
+    if podman ps -a --filter name=^$CONTAINER_NAME$ --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
+        echo "Container $CONTAINER_NAME già in uso o esistente."
+        # process with this specific container already run, skip it
+        echo -e "container $CONTAINER_NAME already in use"
     else
-        # process with this specific docker container already run, skip it
-        echo -e "docker container $DOCKERCONTAINER$COUNTER already in use"
+        echo -e "founded empty docker container: $CONTAINER_NAME"
+        break
     fi
 done
+
+if [ $COUNTER -ge $MAX_COUNTER ]; then
+    echo "Error: No one empty container found in $MAX_COUNTER attempts."
+    exit 1
+fi
 
 # add this lines for proxy
 # -e "HTTP_PROXY=<host>:<port>" \
 # -e "HTTPS_PROXY=<host>:<port>" \
 
 # run docker with specific docker container founded
-docker run \
- --name $DOCKERCONTAINER$COUNTER \
+podman run \
+ --name $CONTAINER_NAME \
  --net=host \
  -it --rm \
  -e "DISPLAY=$DISPLAY" \
